Adding ModelBinding to Web
queoGmbH/csharp-commons.web pull request #1
Opened 2024-06-14 16:36 UTC by PhilippRiegelmann

2024-06-25 15:46 UTC, uoehm requested changes
Ich fände es gut, wenn wir insbesondere für das Laden der Entitäten ein paar  Tests schreiben könnten.

2024-06-25 15:46 UTC, uoehm commented on src/Commons.Web.ModelBinding/ModelBinding/EntityLoader.cs
> +                        object daoInstance = Activator.CreateInstance(type)!;
Ich denke nicht, dass dies in der Form korrekt funktioniert. Wir müssten eigentlich über die ServiceCollection gehen und uns den DAO holen, da diesem ansonsten der DbContext fehlt.

2024-06-25 15:46 UTC, uoehm commented on src/Commons.Web.ModelBinding/ModelBinding/JsonEntityConverter.cs
> +        public override void Write(Utf8JsonWriter writer, TEntity value, JsonSerializerOptions options)
Müssen wir diese Methode überschreiben?
Falls ja würde ich hier gern zwei Aspekte reinbringen:
- Werden Attribute an Properties, die die Serialisierung steuern korrekt beachtet?
- Könnten wir die technische ID (also DB Primary Key) per Option rauslassen?

2024-06-26 12:47 UTC, PhilippRiegelmann commented on src/Commons.Web.ModelBinding/ModelBinding/JsonEntityConverter.cs
> +        public override void Write(Utf8JsonWriter writer, TEntity value, JsonSerializerOptions options)
Schaue ich mir an.

2024-07-03 10:07 UTC, PhilippRiegelmann commented on src/Commons.Web.ModelBinding/ModelBinding/JsonEntityConverter.cs
> +        public override void Write(Utf8JsonWriter writer, TEntity value, JsonSerializerOptions options)
Methode muss überschrieben werden.
Aktuell werden durch den Converter Properties nicht berücksichtigt. 
Die technische ID können wir per Option rauslassen.

2024-07-24 14:48 UTC, uoehm approved these changes

2024-07-26 09:38 UTC, merged